FROM python:3.11-slim

WORKDIR /app
COPY backend /app/backend
WORKDIR /app/backend
RUN pip install -e ".[dev]"

CMD ["uvicorn", "app_template.main:app", "--app-dir", "src", "--host", "0.0.0.0", "--port", "8000"]
